# Generated by Django 5.2.6 on 2025-11-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_category_icon'),
    ]

    operations = []
