# Generated by Django 5.2.12 on 2026-03-31 07:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_remove_shopcategory_category_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AddField(
            model_name='shop',
            name='delivery_charge_per_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Delivery charge in rupees per km (only used when delivery is enabled).', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='shop',
            name='offers_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='offers_pickup',
            field=models.BooleanField(default=True),
        ),
    ]
