# Generated by Django 5.2.12 on 2026-04-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_order_status_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='image',
        ),
    ]
